### ISSUE TITLE
(mac user) Initialize lights no respond

### ISSUE THREAD

**Issue by owenchiouu** [raganmd/touchdesigner-hueControl#24]
Hello! I have no coding background and I'm trying to use this TOX on touchdesigner.

The Link to Bridge process worked where the DeviceUserName and ClientKey appeared after linking, but after clicking initialize lights nothing happen and so the control doesn't work at all.

Things I think that might have caused the problem:
1. Mac M3 Pro?
2. I uses two lightbulbs: a philips hue white light/innr colour bulb that can be used on philips hue
3. An updated was installed while setting up the philips hue bridge

Thank you for this code, I really wish it could work for me as it is so porwerful and I would benefit greatly using this for my bachelor degree show!!! Wondering if anyone might know what happened? Thank you, once again

**Comment by owenchiouu** [comment]
<img width="432" alt="Screenshot 2024-04-29 at 21 18 44" src="https://github.com/raganmd/touchdesigner-hueControl/assets/168481566/d5c63e2a-10b9-4e49-9ce1-b0b83a00255c">
after connecting, nothing happens after pressing Initialize Lights

**Comment by raganmd** [comment]
hi @owenchiouu - thanks for logging the report here. After you've initialized lights what do you see on the control pages for "all lights" and "individual lights"?

Usually it's getting this far that's the hard part.

You might also try saving your project network, and then restarting to the project to see if there's a problem with the initial connection.

You can also remove this TOX, and start the connection process over again. If there was an issue due to a system update that should resolve that problem.

**Comment by raganmd** [comment]
hey @owenchiouu - I'm going to give this issue a few more days, and then I'm going to close it since I haven't heard back about if there need to be any changes.

**Comment by owenchiouu** [comment]
Hi @raganmd ,
Sorry for not updating on my side!
So for now I have tried to save/reconnect, and as usual I have the device user name and client key up after connecting succesfully. However, the initial light pulse seems to not do anything :(
I have also tested on another laptop, but I think the main reason here is that I'm using mainly a Philips hue warm white bulb, where only the brightness can be controlled. Not sure! 
![IMG_6822](https://github.com/raganmd/touchdesigner-hueControl/assets/168481566/9019caba-d67f-4606-ba81-b87cb93694a6)
![IMG_6823](https://github.com/raganmd/touchdesigner-hueControl/assets/168481566/6e2ebf79-40c5-40c9-b26c-80f99c383b11)
![IMG_6824](https://github.com/raganmd/touchdesigner-hueControl/assets/168481566/79515173-5f2d-415f-a48a-8ef1c0a66cc3)
<img width="540" alt="Screenshot 2024-05-07 at 22 13 14" src="https://github.com/raganmd/touchdesigner-hueControl/assets/168481566/b0c7c23c-4e99-4dbf-9fc7-eecce8e624a3">


Thank you once again, and attaching some screenshots and pictures :)


https://github.com/raganmd/touchdesigner-hueControl/assets/168481566/5345b26e-9e7b-4d10-8c87-9c2579c35456

0">

**Comment by raganmd** [comment]
@owenchiouu interesting - I haven't tested with only the warm lights. So there could be something there. Unfortunately, I don't have one of those to test with.

Can you share a screen shot of what you see on this tab of the hue tox?

![Screenshot 2024-05-07 161147](https://github.com/raganmd/touchdesigner-hueControl/assets/11582808/b9db4d3e-aff0-4968-9ac0-6a1108d83494)

Also  - is anything printed in the text port?

It does seem like we're doing a handshake with the hue bridge and lights, so that's good news... I just don't happen to know if the warm lights behave differently than the full color lights.

**Comment by raganmd** [comment]
@owenchiouu - your video finally loaded for me. Now I can see that there's nothing on those pages. That's super strange - do you get any errors? Without having one of these warm only lights I don't have a good way to test what might be happening here.

**Comment by VertigoCorp** [comment]
Hi @raganmd, thank you for addressing the issue of @owenchiouu. I have a comparable situation and can add this textport behavior to the situation, where I have succesfully linked the bridge with a device user name and client key generated.

The all light and the individual lights tabs do not show any newly created parameters after linking to the bridge.
Most of the lights are non-colored only warm/cool white (white ambience), but some of the lights are colored (colored strips in mono-color and in multi color gradient).

When running the Initializelights command, the Textport returns:

```python
running Initializelights
Traceback (most recent call last):
  File "</project1/base_hueControl/pargroupexec_hue_controller>", line "args[0].Add_pars_for_lights()"
  File "/project1/base_hueControl/TDHueControllerEXT", line 234, in Add_pars_for_lights
  File "/project1/base_hueControl/TDHueControllerEXT", line 239, in _add_light_pars
AttributeError: 'NoneType' object has no attribute 'get'
python >>> 
```

>TouchDesigner  Build 2023.11600 compile on Mon Mar  4 18:23:05 2024, on Macbook Pro M3
Python 3.11.1

Furthermore I have a Hue account to get to the bridge-app on phone.

Would you have any clue in a solving direction?

**Comment by raganmd** [comment]
@VertigoCorp - I think the issue here is probably anchored in the difference for the lights that are warm / cool rather than RGB. I think the only way to get to the bottom of this is to test with one of those fixtures.

How comfortable with Python are you? Happy to point you to where you might make some updates to the extension code.

**Comment by NilsJohannesson** [comment]
@raganmd I did some research after getting the same issue on windows. I have both rgb and ambiance white lamps so could see the difference quite clearly. I was trying to adjust the code to account for the different json data but I'm not a python expert and figured it's better to tell you about it since you know it better. 

For an rgb light the color response looks like this (the one you know):
```
            "color": {
                "xy": {
                    "x": 0.4622,
                    "y": 0.2982
                }, etc etc
```

and for ambiance light it looks like this (instead of xy it uses mirek values ??) 
```
            "color_temperature": {
                "mirek": 406,
                "mirek_valid": true,
                "mirek_schema": {
                    "mirek_minimum": 153,
                    "mirek_maximum": 454
                }
            }, etc etc
```

I'll include the full responses below. Hoping this makes the changes very obvious for you. I am not familiar with the term mirek or how that translates to color temps, but it seems like gradient going from 153 (cold) to 454 (warm). 

Hope this helps!

Cheers,
Nils

[RGBLight_response.json](https://github.com/user-attachments/files/17118440/RGBLight_response.json)
[AmbianceLight_response.json](https://github.com/user-attachments/files/17118441/AmbianceLight_response.json)

**Comment by raganmd** [comment]
@NilsJohannesson oh sheesh.

So fun fact about phillips Hue RGB lamps color is represented as an xy value on the device, which has a conversion that looks like this: 

https://gist.github.com/bgromov/d721f020694abda3ad3dba0c49113376

You'll see in the extension that I currently convert from a set of color pars to xy, and back to pars to make this bit work.

It looks like the color temperature fixtures instead use a Mirek color temperature that's instead represented as a single integer in the range of 153 to 500.

That does give me a better hint here - I can't say for sure when I'll be able to update this. I'd probably need to get my hands on a lamp to actually test, and I need to rethink how those parameters get generated to account a different control schema. 

🤔
